#!/usr/bin/env python3
"""
agent.py — Agent Laguna main orchestrator.

Coordinates the daily cycle:
  1. Hexflow contract processing (shuttle engine integration)
  2. Daily task execution (inbox, gems, heartbeat tasks)
  3. Self-improvement (1 step per day, Scientific Method)
  4. Hounty reward tracking
  5. Daily completion + personalization

Runs as a daily cron job or loop. Stdlib-only (no external dependencies).
"""
import json
import os
import sys
import time
import hashlib
from pathlib import Path
from datetime import datetime, timezone

HOME = Path.home()
LAGUNA_DIR = HOME / ".agent_laguna"
AGENT_LAGUNA_DIR = Path(__file__).parent

# Import sibling modules
sys.path.insert(0, str(AGENT_LAGUNA_DIR))
import hexflow_contract  # noqa: E402
import hounty  # noqa: E402
import self_improve  # noqa: E402
import daily_task  # noqa: E402
import github_integration as gh  # noqa: E402


def _now_iso():
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _today_str():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _ensure_dirs():
    LAGUNA_DIR.mkdir(parents=True, exist_ok=True)
    (LAGUNA_DIR / "logs").mkdir(parents=True, exist_ok=True)


def _log(msg: str):
    _ensure_dirs()
    log_file = LAGUNA_DIR / "logs" / "agent.log"
    entry = f"[{_now_iso()}] {msg}\n"
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(entry)
    print(entry, end="")


def initialize() -> dict:
    """Initialize Agent Laguna — create directories and default configs."""
    _ensure_dirs()

    # Default config
    config = {
        "agent_id": "agent-laguna",
        "version": "1.0.0",
        "hexflow_integration": True,
        "hounty_enabled": True,
        "daily_personalization": True,
        "self_improve_daily": True,
        "max_inbox_actions_per_cycle": 9,
        "created": _now_iso(),
    }
    config_file = LAGUNA_DIR / "config.json"
    if not config_file.exists():
        config_file.write_text(json.dumps(config, indent=2), encoding="utf-8")
    _log(f"Agent Laguna initialized (ID: {config['agent_id']})")
    return config


def github_heartbeat() -> dict:
    """GitHub heartbeat — sync issues to inbox and post results.

    Runs at the start of each daily cycle:
      1. Sync open GitHub issues with 'task' label into Aegis inbox
      2. Create GitHub issues for today's completed tasks
      3. Post result comments on existing task issues
    """
    _log("→ Phase 0: GitHub heartbeat")
    gh_result = {
        "auth": None,
        "synced_issues": 0,
        "issues_created": 0,
        "comments_posted": 0,
    }

    # Check gh auth
    auth = gh.gh_auth_status()
    gh_result["auth"] = auth["success"]
    if not auth["success"]:
        _log(f"   GitHub: gh auth failed — {auth.get('stderr', 'unknown error')}")
        return gh_result

    # 1. Sync open issues to inbox
    synced = gh.sync_issues_to_inbox()
    gh_result["synced_issues"] = synced
    _log(f"   GitHub: synced {synced} issue(s) to inbox")

    return gh_result


def post_github_results(result: dict) -> dict:
    """Post daily cycle results to GitHub as issue comments."""
    post_result = {"issues_created": 0, "comments_posted": 0}

    # Create an issue for today's cycle summary
    today = _today_str()
    summary_title = f"Daily Cycle — {today}"
    summary_body = f"""## Agent Laguna Daily Cycle — {today}

**Timestamp:** {_now_iso()}

### Hexflow
- Stage: {result.get('hexflow', {}).get('hex_stage', 'N/A')}
- Completed: {result.get('hexflow', {}).get('completed', False)}

### Tasks
- Inbox actions: {len(result.get('tasks', {}).get('inbox_actions', []))}
- Gems harvested: {len(result.get('tasks', {}).get('gem_processing', []))}
- Heartbeat tasks: {len(result.get('tasks', {}).get('heartbeat_tasks', []))}

### Self-Improvement
- {result.get('self_improvement', {}).get('area', 'N/A')}: {result.get('self_improvement', {}).get('verdict', 'N/A')}

### Hounty
- Before: {result.get('hounty_before', {}).get('total_points', 0)} points
- After: {result.get('hounty_after', {}).get('total_points', 0)} points
- Streak: {result.get('hounty_after', {}).get('current_streak', 0)} days

*Auto-generated by Agent Laguna*
"""
    url = gh.create_issue(
        summary_title, summary_body,
        labels=["daily-cycle", "auto-generated"]
    )
    if url:
        post_result["issues_created"] = 1
        _log(f"   GitHub: created daily cycle issue — {url}")

    # Post self-improvement as a comment on its own issue
    si = result.get("self_improvement", {})
    if si.get("verdict") and si.get("status") != "already_done":
        # Find or create the self-improvement issue
        si_issues = gh.list_issues(labels="self-improvement")
        if si_issues:
            issue_num = si_issues[0]["number"]
        else:
            url = gh.create_issue(
                "[Self-Improvement] Daily improvement log",
                f"## Self-Improvement Tracking\n\nThis issue tracks daily self-improvement steps.",
                labels=["self-improvement", "tracking"]
            )
            if url:
                si_issues = gh.list_issues(labels="self-improvement")
                issue_num = si_issues[0]["number"] if si_issues else None

        if si_issues:
            comment = f"""### {today} — {si.get('area', 'unknown')}

**Hypothesis:** {si.get('hypothesis', 'N/A')}
**Change:** {si.get('change', 'N/A')}
**Verdict:** {si.get('verdict', 'N/A')} — {si.get('note', 'N/A')}
**Delta:** {si.get('delta', 0)} points

_Measured baseline: {si.get('baseline', {}).get('baseline_points', 'N/A')} → After: {si.get('after_points', 'N/A')}_
"""
            if gh.comment_on_issue(str(issue_num), comment):
                post_result["comments_posted"] += 1

    return post_result


def run_daily() -> dict:
    """Execute one full daily cycle for Agent Laguna.

    Phases:
      0. GitHub heartbeat — sync issues to inbox
      1. Hexflow contract processing — advance shuttle through stages
      2. Daily task execution — inbox actions, gems, heartbeat tasks
      3. Self-improvement — 1 Scientific Method step per day
      4. Hounty tracking + GitHub result posting
    """
    _log("═══ Starting daily cycle ═══")

    result = {
        "date": _today_str(),
        "timestamp": _now_iso(),
        "github_heartbeat": None,
        "hexflow": None,
        "tasks": None,
        "self_improvement": None,
        "github_results": None,
        "hounty_before": {},
        "hounty_after": {},
        "completed": True,
    }

    # Capture hounty before
    result["hounty_before"] = hounty.balance()

    # Phase 0: GitHub heartbeat
    result["github_heartbeat"] = github_heartbeat()

    # Phase 1: Hexflow contract processing
    _log("→ Phase 1: Hexflow contract processing")
    hexflow_result = hexflow_contract.run_hexflow_cycle()
    result["hexflow"] = hexflow_result
    _log(f"   Hexflow: stage={hexflow_result.get('hex_stage')}, "
         f"completed={hexflow_result.get('completed')}")

    # Award hounty for hexflow progress
    if hexflow_result.get("completed"):
        hounty.award_hexflow_step("COMMIT")
    else:
        stage = hexflow_result.get("hex_stage", "INGEST")
        hounty.award_hexflow_step(stage)

    # Phase 2: Daily task execution
    _log("→ Phase 2: Daily task execution")
    task_result = daily_task.run_daily_cycle()
    result["tasks"] = task_result

    # Phase 3: Self-improvement (1 step per day)
    _log("→ Phase 3: Self-improvement check")
    si_result = self_improve.execute_self_improvement()
    result["self_improvement"] = si_result
    if si_result.get("status") != "already_done":
        hounty.award_self_improvement()

    # Capture hounty after
    result["hounty_after"] = hounty.balance()

    # Phase 4: GitHub result posting
    _log("→ Phase 4: GitHub result posting")
    result["github_results"] = post_github_results(result)

    # Record completion
    _log(f"→ Daily cycle complete. Points: "
         f"{result['hounty_before']['total_points']} → "
         f"{result['hounty_after']['total_points']}")

    # Save daily result
    _ensure_dirs()
    result_file = LAGUNA_DIR / "daily_results" / f"{_today_str()}.json"
    result_file.parent.mkdir(parents=True, exist_ok=True)
    result_file.write_text(json.dumps(result, indent=2), encoding="utf-8")

    _log("═══ Daily cycle complete ═══\n")
    return result


def run_loop(interval_hours: int = 24, max_iterations: int = 0) -> None:
    """Run Agent Laguna in a continuous loop.

    By default, runs once per day (24h interval). Set max_iterations > 0
    for testing.
    """
    initialize()
    iteration = 0
    _log(f"Agent Laguna loop started (interval: {interval_hours}h)")

    while True:
        iteration += 1
        _log(f"Loop iteration {iteration}")

        try:
            run_daily()
            hounty.award(50, "daily_cycle_complete", "daily")
        except Exception as e:
            _log(f"ERROR in daily cycle: {e}")
            hounty.award(-25, f"cycle_error: {type(e).__name__}", "error")

        if max_iterations > 0 and iteration >= max_iterations:
            _log(f"Reached max iterations ({max_iterations}), stopping.")
            break

        _log(f"Sleeping {interval_hours}h until next cycle...")
        time.sleep(interval_hours * 3600)


def status() -> dict:
    """Return Agent Laguna status."""
    config_file = LAGUNA_DIR / "config.json"
    config = {}
    if config_file.exists():
        config = json.loads(config_file.read_text(encoding="utf-8"))

    return {
        "agent_id": config.get("agent_id", "agent-laguna"),
        "version": config.get("version", "unknown"),
        "status": "running" if self_improve._load_improvement_history() else "initialized",
        "hounty": hounty.balance(),
        "hexflow": hexflow_contract.status(),
        "today": _today_str(),
        "uptime": config.get("created", "unknown"),
    }


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "init"

    if cmd == "init":
        print(json.dumps(initialize(), indent=2))
    elif cmd == "daily":
        print(json.dumps(run_daily(), indent=2))
    elif cmd == "loop":
        interval = int(sys.argv[2]) if len(sys.argv) > 2 else 24
        max_iter = int(sys.argv[3]) if len(sys.argv) > 3 else 0
        run_loop(interval, max_iter)
    elif cmd == "status":
        print(json.dumps(status(), indent=2))
    elif cmd == "github":
        sub = sys.argv[2] if len(sys.argv) > 2 else "summary"
        if sub == "summary":
            print(json.dumps(gh.issue_summary(), indent=2))
        elif sub == "sync":
            count = gh.sync_issues_to_inbox()
            print(f"Synced {count} issues to inbox")
        elif sub == "create":
            title = sys.argv[3] if len(sys.argv) > 3 else "Agent Laguna Task"
            body = sys.argv[4] if len(sys.argv) > 4 else "Created by Agent Laguna"
            url = gh.create_issue(title, body, labels=["task", "auto-generated"])
            print(f"Issue: {url}")
        elif sub == "list":
            issues = gh.list_issues(state="open")
            for i in issues:
                print(f"#{i['number']}: {i['title']} — {i['url']}")
        else:
            print(f"Usage: python agent.py github [summary|sync|create <title> <body>|list]")
    else:
        print(f"Usage: python agent.py [init|daily|loop [hours] [max_iter]|status|github]")
        print(f"  init    — Initialize Agent Laguna")
        print(f"  daily   — Run one daily cycle")
        print(f"  loop    — Run continuously (default: 24h interval)")
        print(f"  status  — Show current status")
        print(f"  github  — GitHub integration (summary|sync|create|list)")
